

  // =============================== //
 // Song-Datenbank (selbst gebaut)  //
// =============================== //

// Enthält alle Songs mit ihren Noten, Timing-Daten und Schwierigkeitsgraden.

const songs = {
    "Nirvana": {
        "Come As You Are": {                                            // Definiert einen Song mit Audio-Pfad, BPM, Verzögerung und Notenabfolge.
            audioPath: "music/Nirvana_Come_As_You_Are.mp3",             // Pfad der Audio-Datei
            delayAudio : 1100,                                          // Delay wie die Audio-Datei abgespielt werden soll
            bpm: 120,                                                   // Tempo des Songs in Beats per Minute
            sequence: [                                                 // Beschreibt die Abfolge der Riffs im Song mit Verzögerungen.
                { riff: "introRiff", delay: 0 },                        // Intro-Riff ohne Verzögerung
                { riff: "verseRiff", delay: 4750 },                     // Verse-Riff nach 4750 ms
                { riff: "verseRiff", delay: 8750 },
                { riff: "verseRiff", delay: 12750 },
                { riff: "verseRiff", delay: 16750 },
                { riff: "verseRiff", delay: 20750 },
                { riff: "verseRiff", delay: 24750 },
                { riff: "verseRiff", delay: 28750 },
                { riff: "verseRiff", delay: 32750 },
                { riff: "verseRiff", delay: 36750 },
                { riff: "verseRiff", delay: 40750 },
                { riff: "verseRiff", delay: 44750 },
                { riff: "bridgeRiff", delay: 48750 },
                { riff: "bridgeRiff", delay: 52750 },
                { riff: "bridgeRiff", delay: 56750 },
                { riff: "bridgeRiff", delay: 60750 },
                { riff: "verseRiff", delay: 64750 },
                { riff: "verseRiff", delay: 68750 },
                { riff: "verseRiff", delay: 72750 },
                { riff: "verseRiff", delay: 76750 },
                { riff: "bridgeRiff", delay: 80750 },
                { riff: "bridgeRiff", delay: 84750 },
                { riff: "bridgeRiff", delay: 88750 },
                { riff: "bridgeRiff", delay: 92750 },
                { riff: "chorusRiff", delay: 96750 },
                { riff: "chorusRiff", delay: 100750 },
                { riff: "chorusRiff", delay: 104750 },
                { riff: "chorusRiff", delay: 108750 },
                { riff: "verseRiff", delay: 112750 },
                { riff: "verseRiff", delay: 116750 },
                { riff: "soloRiff", delay: 120750 },
                { riff: "soloRiff", delay: 128500 },
                { riff: "soloRiff", delay: 136250 },
                { riff: "soloRiff", delay: 144000 },
                { riff: "bridgeRiff", delay: 152000 },
                { riff: "bridgeRiff", delay: 156000 },
                { riff: "bridgeRiff", delay: 160000 },
                { riff: "bridgeRiff", delay: 164000 },
                { riff: "chorusRiff", delay: 168000 },
                { riff: "chorusRiff", delay: 172000 },
                { riff: "chorusRiff", delay: 176000 },
                { riff: "chorusRiff", delay: 180000 },
                { riff: "endChorusRiff", delay: 183750 },
                { riff: "endChorusRiff", delay: 187500 },
                { riff: "verseRiff", delay: 191500 },
                { riff: "verseRiff", delay: 195500 },
                { riff: "verseRiff", delay: 199500 },
                { riff: "verseRiff", delay: 203500 },
                { riff: "outroRiff", delay: 207500 },
            ],
            introRiff: [                                                // Enthält die Noten eines Riffs mit Timing und Schwierigkeitsgrad.
                { key: "A", time: 0, difficulty: "easy" },
                { key: "A", time: 250, difficulty: "medium" },
                { key: "S", time: 500, difficulty: "hard" },
                { key: "D", time: 750, difficulty: "easy" },
                { key: "F", time: 1250, difficulty: "easy" },
                { key: "D", time: 1500, difficulty: "hard" },
                { key: "F", time: 1750, difficulty: "medium" },
                { key: "D", time: 2000, difficulty: "hard" },
                { key: "D", time: 2250, difficulty: "medium" },
                { key: "S", time: 2500, difficulty: "hard" },
                { key: "A", time: 2750, difficulty: "easy" },
                { key: "G", time: 3000, difficulty: "hard" },
                { key: "A", time: 3250, difficulty: "medium" },
                { key: "A", time: 3500, difficulty: "easy" },
                { key: "G", time: 4000, difficulty: "easy" },
                { key: "A", time: 4250, difficulty: "medium" },
                { key: "S", time: 4500, difficulty: "hard" }
            ],
            verseRiff: [
                { key: "D", time: 0, difficulty: "easy" },
                { key: "F", time: 500, difficulty: "easy" },
                { key: "D", time: 750, difficulty: "hard" },
                { key: "F", time: 1000, difficulty: "medium" },
                { key: "D", time: 1250, difficulty: "hard" },
                { key: "D", time: 1500, difficulty: "medium" },
                { key: "S", time: 1750, difficulty: "hard" },
                { key: "A", time: 2000, difficulty: "easy" },
                { key: "G", time: 2250, difficulty: "hard" },
                { key: "A", time: 2500, difficulty: "medium" },
                { key: "A", time: 2750, difficulty: "easy" },
                { key: "G", time: 3250, difficulty: "easy" },
                { key: "A", time: 3500, difficulty: "medium" },
                { key: "S", time: 3750, difficulty: "hard" },
            ],
            bridgeRiff: [
                { key: "S", time: 0, difficulty: "easy" },
                { key: "S", time: 500, difficulty: "medium" },
                { key: "S", time: 750, difficulty: "easy" },
                { key: "S", time: 1250, difficulty: "medium" },
                { key: "S", time: 1500, difficulty: "medium" },
                { key: "S", time: 1750, difficulty: "medium" },
                { key: "F", time: 2000, difficulty: "easy" },
                { key: "F", time: 2250, difficulty: "medium" },
                { key: "F", time: 2500, difficulty: "easy" },
                { key: "F", time: 2750, difficulty: "medium" },
                { key: "F", time: 3250, difficulty: "medium" },
                { key: "F", time: 3500, difficulty: "easy" },
                { key: "F", time: 3750, difficulty: "medium" },
            ],
            chorusRiff: [
                { key: "D", time: 0, difficulty: "easy" },
                { key: "D", time: 250, difficulty: "medium" },
                { key: "D", time: 500, difficulty: "easy" },
                { key: "D", time: 750, difficulty: "medium" },
                { key: "D", time: 1000, difficulty: "easy" },
                { key: "D", time: 1250, difficulty: "medium" },
                { key: "D", time: 1500, difficulty: "easy" },
                { key: "D", time: 1750, difficulty: "medium" },
                { key: "G", time: 2000, difficulty: "easy" },
                { key: "G", time: 2250, difficulty: "medium" },
                { key: "G", time: 2500, difficulty: "easy" },
                { key: "G", time: 2750, difficulty: "medium" },
                { key: "G", time: 3000, difficulty: "easy" },
                { key: "G", time: 3250, difficulty: "medium" },
                { key: "G", time: 3500, difficulty: "easy" },
                { key: "G", time: 3750, difficulty: "medium" },
            ],
            soloRiff: [
                { key: "S", time: 0, difficulty: "easy" },
                { key: "D", time: 750, difficulty: "easy" },
                { key: "F", time: 1250, difficulty: "easy" },
                { key: "S", time: 2000, difficulty: "easy" },
                { key: "D", time: 2750, difficulty: "easy" },
                { key: "F", time: 3250, difficulty: "easy" },
                { key: "S", time: 4000, difficulty: "easy" },
                { key: "D", time: 4750, difficulty: "easy" },
                { key: "F", time: 5250, difficulty: "easy" },
                { key: "G", time: 5750, difficulty: "easy" },
                { key: "F", time: 6750, difficulty: "easy" },
                { key: "D", time: 7250, difficulty: "easy" },
            ],
            soloRiffHigh: [
            ],
            endChorusRiff: [
                { key: "D", time: 0, difficulty: "easy" },
                { key: "D", time: 250, difficulty: "medium" },
                { key: "D", time: 500, difficulty: "easy" },
                { key: "D", time: 750, difficulty: "medium" },
                { key: "D", time: 1000, difficulty: "easy" },
                { key: "D", time: 1250, difficulty: "medium" },
                { key: "D", time: 1500, difficulty: "easy" },
                { key: "D", time: 1750, difficulty: "medium" },
                { key: "G", time: 2000, difficulty: "easy" },
                { key: "G", time: 2250, difficulty: "medium" },
                { key: "G", time: 2500, difficulty: "easy" },
                { key: "G", time: 2750, difficulty: "medium" },
                { key: "G", time: 3000, difficulty: "easy" },
                { key: "G", time: 3250, difficulty: "medium" },
                { key: "G", time: 3500, difficulty: "easy" },
            ],
            outroRiff: [
                { key: "A", time: 0, difficulty: "easy" }
            ],
        }
    },
    "The White Stripes": {                                              // zweiter Song
        "Seven Nation Army": {
            audioPath: "music/The_White_Stripes_Seven_Nation_Army.mp3",
            delayAudio : 0,
            bpm: 122,
            sequence: [            
                { riff: "introRiff", delay: 1072 },
                { riff: "introRiff", delay: 5082.7 },
                { riff: "introRiff", delay: 9067.8 },
                { riff: "introRiff", delay: 12859.1 },
                { riff: "verseRiff", delay: 16650.3 },
                { riff: "verseRiff", delay: 20456.4 },
                { riff: "verseRiff", delay: 24325.5 },
                { riff: "verseRiff", delay: 28194.8 },
                { riff: "verseRiff", delay: 32064.4 },
                { riff: "verseRiff", delay: 35889.3 },
                { riff: "verseRiff", delay: 39696.6 },
                { riff: "verseRiff", delay: 43640 },
                { riff: "bridgeRiff", delay: 47500 },
                { riff: "chorusRiff", delay: 51424.4 },
                { riff: "chorusRiff", delay: 59450 },
                { riff: "bridgeRiff", delay: 67450 },
                { riff: "verseRiff", delay: 71300 },
                { riff: "verseRiff", delay: 75280 },
                { riff: "verseRiff", delay: 79260 },
                { riff: "verseRiff", delay: 83300 },
                { riff: "verseRiff", delay: 87360 },
                { riff: "verseRiff", delay: 91300 },
                { riff: "verseRiff", delay: 95300 },
                { riff: "verseRiff", delay: 99200 },
                { riff: "verseRiff", delay: 102800 },
                { riff: "verseRiff", delay: 106800 },
                { riff: "verseRiff", delay: 110700 },
                { riff: "verseRiff", delay: 114400 },
                { riff: "bridgeRiff", delay: 118500},
                { riff: "soloRiff", delay: 122400},
                { riff: "soloRiff", delay: 130000},
                { riff: "soloRiffHigh", delay: 138000},
                { riff: "soloRiffHigh", delay: 146000},
                { riff: "bridgeRiff", delay: 154000 },
                { riff: "verseRiff", delay: 157760 },
                { riff: "verseRiff", delay: 161730 },
                { riff: "verseRiff", delay: 165700 },
                { riff: "verseRiff", delay: 169750 },
                { riff: "verseRiff", delay: 173800 },
                { riff: "verseRiff", delay: 177850 },
                { riff: "verseRiff", delay: 181850 },
                { riff: "verseRiff", delay: 185800 },
                { riff: "verseRiff", delay: 189400 },
                { riff: "verseRiff", delay: 193400 },
                { riff: "verseRiff", delay: 197200 },
                { riff: "verseRiff", delay: 200900 },
                { riff: "bridgeRiff", delay: 204970 },
                { riff: "chorusRiff", delay: 208940 },
                { riff: "chorusRiff", delay: 216940 }
            ],
            introRiff: [
                { key: "F", time: 0, difficulty: "easy" },
                { key: "F", time: 761.25, difficulty: "medium" },
                { key: "G", time: 1016.7, difficulty: "easy" },
                { key: "F", time: 1398.125, difficulty: "medium" },
                { key: "D", time: 1779.125, difficulty: "medium" },
                { key: "S", time: 2033.4, difficulty: "easy" },
                { key: "A", time: 3050.1, difficulty: "easy" },
            ],
            verseRiff: [
                { key: "F", time: 0, difficulty: "easy" },
                { key: "F", time: 761.25, difficulty: "medium" },
                { key: "G", time: 1016.7, difficulty: "easy" },
                { key: "F", time: 1398.125, difficulty: "medium" },
                { key: "D", time: 1779.125, difficulty: "medium" },
                { key: "S", time: 2033.4, difficulty: "easy" },
                { key: "A", time: 3050.1, difficulty: "easy" },
            ],
            bridgeRiff: [
                { key: "S", time: 0, difficulty: "easy" },     
                { key: "S", time: 245.9, difficulty: "hard" },
                { key: "S", time: 491.8, difficulty: "medium" },
                { key: "S", time: 737.7, difficulty: "hard" },
                { key: "S", time: 983.6, difficulty: "easy" },
                { key: "S", time: 1229.5, difficulty: "hard" }, 
                { key: "S", time: 1475.4, difficulty: "medium" }, 
                { key: "S", time: 1711.3, difficulty: "hard" },
                { key: "F", time: 1957.2, difficulty: "easy" },
                { key: "F", time: 2203.1, difficulty: "hard" },
                { key: "F", time: 2449, difficulty: "medium" },
                { key: "F", time: 2694.9, difficulty: "hard" },
                { key: "F", time: 2940.8, difficulty: "easy" },
                { key: "F", time: 3186.7, difficulty: "hard" },
                { key: "F", time: 3432.6, difficulty: "medium" },
                { key: "F", time: 3678.5, difficulty: "hard" },
            ],
            chorusRiff: [
                { key: "F", time: 0, difficulty: "easy" },
                { key: "F", time: 761.25, difficulty: "medium" },
                { key: "G", time: 1016.7, difficulty: "easy" },
                { key: "F", time: 1398.125, difficulty: "medium" },
                { key: "D", time: 1779.125, difficulty: "medium" },
                { key: "S", time: 2033.4, difficulty: "easy" },
                { key: "A", time: 3050.1, difficulty: "easy" },
                { key: "F", time: 4066.8, difficulty: "easy" },
                { key: "F", time: 4828.05, difficulty: "medium" },
                { key: "G", time: 5083.5, difficulty: "easy" },
                { key: "F", time: 5464.925, difficulty: "medium" },
                { key: "D", time: 5845.925, difficulty: "easy" },
                { key: "S", time: 6099.15, difficulty: "medium" },
                { key: "D", time: 6353.17, difficulty: "medium" },
                { key: "S", time: 6734.51, difficulty: "easy" },
                { key: "A", time: 7115.85, difficulty: "easy" },
            ],
            soloRiff: [
                { key: "S", time: 0, difficulty: "easy" },
                { key: "S", time: 761.25, difficulty: "medium" },
                { key: "S", time: 1016.7, difficulty: "medium" },
                { key: "F", time: 1398.125, difficulty: "easy" },
                { key: "D", time: 1779.125, difficulty: "medium" },
                { key: "S", time: 2033.4, difficulty: "easy" },
                { key: "A", time: 3050.1, difficulty: "easy" },
                { key: "S", time: 4066.8, difficulty: "easy" },
                { key: "S", time: 4828.05, difficulty: "medium" },
                { key: "G", time: 5083.5, difficulty: "easy" },
                { key: "F", time: 5464.925, difficulty: "medium" },
                { key: "D", time: 5845.925, difficulty: "medium" },
                { key: "S", time: 6099.15, difficulty: "medium" },
                { key: "D", time: 6353.17, difficulty: "easy" },
                { key: "S", time: 6734.51, difficulty: "easy" },
                { key: "A", time: 7115.85, difficulty: "easy" },
            ],
            soloRiffHigh: [
                { key: "D", time: 0, difficulty: "easy" },
                { key: "D", time: 761.25, difficulty: "medium" },
                { key: "D", time: 1016.7, difficulty: "medium" },
                { key: "G", time: 1398.125, difficulty: "easy" },
                { key: "F", time: 1779.125, difficulty: "medium" },
                { key: "D", time: 2033.4, difficulty: "easy" },
                { key: "S", time: 3050.1, difficulty: "easy" },
                { key: "D", time: 4066.8, difficulty: "easy" },
                { key: "D", time: 4828.05, difficulty: "medium" },
                { key: "G", time: 5083.5, difficulty: "easy" },
                { key: "G", time: 5464.925, difficulty: "medium" },
                { key: "F", time: 5845.925, difficulty: "medium" },
                { key: "D", time: 6099.15, difficulty: "medium" },
                { key: "S", time: 6353.17, difficulty: "easy" },
                { key: "S", time: 6734.51, difficulty: "easy" },
                { key: "A", time: 7115.85, difficulty: "easy" },
            ],
            endChorusRiff: [
            ],
            outroRiff: [
            ],
        }
    }
};